plugins: chroma fetchart embedart fromfilename discogs
directory: /musiclibrary/music
library: /musiclibrary/beetsmusic.db
art_filename: albumart
threaded: yes

paths:
    default: $albumartist/$album%aunique{}/$title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$title

import:
  write: yes
  move: yes
  resume: yes
  log: /home/abc/.config/beets/import.log
  duplicate_action: merge
  quiet_fallback: asis

match:
  strong_rec_thresh: 0.15

embedart:
  auto: yes
  remove_art_file: yes

fetchart:
  auto: yes

discogs:
  user_token: DISCOGS_TOKEN
